### ISSUE TITLE
ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by shoaib1987** [fingersonfire/Whatsapp-Xtract#1]
I see this error when I run following command,
python Whatsapp_Xtract_V2.1_2012-05-10-2/whatsapp_xtract.py  msgstore-2015-06-09.1.db.crypt8 
Python Version 2.x
Android mode!

trying to repair android database...
trying to decrypt android database...
Traceback (most recent call last):
  File "Whatsapp_Xtract_V2.1_2012-05-10-2/whatsapp_xtract.py", line 2062, in <module>
    main(sys.argv[1:])
  File "Whatsapp_Xtract_V2.1_2012-05-10-2/whatsapp_xtract.py", line 995, in main
    decoded = cipher.decrypt(open(options.infile,"rb").read())
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

**Comment by jasane** [comment]
I have the same problem

**Comment by ria-kedia** [comment]
i have the same. whats the issue with this?

**Comment by wegylexy** [comment]
any update?
